apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ovpn-admin-chart.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ovpn-admin-chart.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ovpn-admin-chart.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ovpn-admin-chart.serviceAccountName" . }}