---
{{- if .Values.ingress.basicAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovpn-admin-chart.fullname" . }}-basic-auth
type: Opaque
data:
  auth: {{ print .Values.ovpnAdmin.basicAuth.user ":{PLAIN}" .Values.ovpnAdmin.basicAuth.password | b64enc | quote }}
{{- end -}}